version: "3"

services:
    express:
        build: ./
        restart: always
        ports:
            - "3300:3000"
        links:
            - database
        networks:
            - default
        depends_on:
            - database

    database:
        image: mongo:latest
        restart: always
        volumes:
            - ./mongodb_data/:/data/db
        expose:
            - "27017"
        networks:
            - default
networks:
    default:
